---
architecture: DenseNet
dataset_name: CIFAR10
batch_size: 64
optimizer:
  name: Momentum
  momentum: 0.9
  use_nesterov: true
learning_rate: 0.1
num_epochs: 300
lr_annealing:
  name: cosine_decay
pre_processing:
  train:
    spatial_pad:
      padding: 4
    random_crop:
      width: 32
      height: 32
    random_flip_left_right: true
  test: {}
growth_rates:
- 32
- 64
- 128
reduction: 0.5
build_method: sandbox
stages:
- 7
- 7
- 7

ranks:
  # pw: c x0 wh x1 n
  # conv: c x0 wh x1 n
- pw:
  - 8
  - 32
  conv:
  - 8
  - 32

- pw:
  - 16
  - 64
  conv:
  - 16
  - 64

- pw:
  - 32
  - 128
  conv:
  - 32
  - 128

dropout_rate: 0
bottleneck: 4
weight_decay: 0.0001
test_every: 1
seed: 0
