architecture: "MobileNetV1"
dataset_name: "CIFAR100"
batch_size: 128

optimizer: "Momentum"
momentum:0.9
use_nesterov: false
learning_rate: 0.1
learning_rate_decay: 0.2
num_epochs_decay: 60
num_epochs: 200
weight_decay: 5e-4
switch_list: [1.0, 0.5]

test_every: 1
seed: 42

